#!/bin/bash

echo
echo
echo "===> Welcome to Solar System"
echo "Developed by Sarah Kreutzer & Daniel Melichar"
echo "5AHITM - SEW"
echo 
echo "===> Initializing..."
echo
echo
echo "===> Setting up virtualenv..."
virtualenv -q --python=python3.5 venv
source venv/bin/activate
echo "===> ...done"
echo
echo "===> Setting up Python requirements..."
pip3 install -q -r requirements.txt
pip3 install -q git+https://github.com/jorgecarleitao/pyglet-gui.git
echo "===> ...done"
echo
echo "===> Generating documentation..."
doxygen
echo "===> ...done"
echo
echo "All finished."
echo "Now ready to use Solar system"